[package]
name = "seo_optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add dependencies from crates.io if needed
natural = "0.5"
tokenize = "0.2.0"

[[bin]]
name = "seo_optimizer"
path = "src/main.rs"
